### ISSUE TITLE
Pinpoint places in the model to perform ablation studies

### ISSUE THREAD

**Issue by ngarneau** [ngarneau/vecmap#10]

**Comment by TortillasAlfred** [comment]
After review, most of the pertinence of ablation studies lies in step 3.3. I believe all four of the points I identified to be of equal interest. However, since there is a number of 7 hyperparameters I found to be worth cross-validating, exploring 5 values for each would leave us to make 5**7=78125 experiments for a complete cross-validation. I suggest we maybe explore each hyperparameter combination at a time while keeping the others fixed. For example, we only explore different values for the vocabulary filtering step while leaving the other parameters intact. This should essentially allow us a more manageable ~200 experiments, all sorted with respect to a single part of the experiment, essentially yielding natural graph curves to highlight hyperparameter stability of the method.  

Step 3.1 : Everything seems normal, only standard whitening transfos.

Step 3.2 :
- Explore using sorted(M_x) instead of sorted(\sqrt(M_x))
- _Maybe compare cosine similarity results_

Step 3.3 : 
- **Stochastic dictionnary induction** :
    - Their procedure is based on following values : _p0_, _p_factor_, _objective_function_tolerance_ and _objective_step_tolerance_. 
    - By default, they assign, in same order as above : [0.1, 2, 1e-6, 50]. Would be interesting to do a cross-validation on those.
- **Vocabulary frequence filtering** : They only keep the top-20'000 words in each language, we could try values around 10'000, 15'000, 20'000, 25'000, 30'000 for example.
- **CSLS** : This method is based on an hyperparameter _k_ of number of nearest neighbours to consider. Would be quite interesting to see what happens if we remove this step and/or try a few other values for _k_.
- Their original solution is built with a sorting of the _top-k_ word from X' and Z', given by step 3.2. Could maybe explore another value for _k_.

Step 3.4 : Same as step 3.1, no real value of an ablation study here.
